server:
  port: 8081


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/career_hive
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 12345

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update

    mail:
      host: ${EMAIL_HOST}
      port: ${EMAIL_PORT}
      username: ${EMAIL_ID}
      password: ${EMAIL_PASSWORD}
      default-encoding: UTF-8
      properties:
        mail:
          mime:
            charset: UTF-8
          smtp:
            writetimeout: 10000
            connectiontimeout: 10000
            timeout: 10000
            auth: true
            starttls:
              enable: true
              required: true
    verify:
      host: ${VERIFY_EMAIL_HOST}


EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: "furkanerenoglu26@gmail.com"
EMAIL_PASSWORD: yyfp ftnj obus pcvx
VERIFY_EMAIL_HOST: http://localhost:8081