server:
  port: 8081


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/career_hive
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 12345

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update